apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-serving-platform.fullname" . }}-registry-config
  labels:
    {{- include "ml-serving-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
data:
  APP_ENV: {{ .Values.registry.env.APP_ENV | quote }}
  DATABASE_URL: {{ .Values.registry.env.DATABASE_URL | quote }}
  MODEL_STORE_PATH: {{ .Values.registry.env.MODEL_STORE_PATH | quote }}
  LOG_LEVEL: {{ .Values.registry.env.LOG_LEVEL | quote }}
