# pvc-registry-data.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
